"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, Building2, Check, ChevronRight, CircleHelp, Clock3, Download, LayoutDashboard, Plus, Receipt, Search, ShieldCheck, Tags, Users, Wallet, X, Activity, Layers3 } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, SidebarInset } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { balance, type Business, type Expense, type View } from '@/lib/model';
import { initialState } from '@/lib/demo';
import { mutate, visibleState } from '@/lib/operations';

const money=(n:number,currency='KES')=>new Intl.NumberFormat('en-KE',{style:'currency',currency,maximumFractionDigits:2,minimumFractionDigits:0}).format(n/100);
const shortDate=(d:string)=>new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const palettes=['#3566ed','#20a995','#f2ac43','#9a72df','#e17a94','#71839e'];
const nav=[['Overview',LayoutDashboard],['Expenses',Receipt],['Approvals',ShieldCheck],['Wallet',Wallet],['Categories',Tags],['Team',Users],['Activity',Activity]] as const;
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Status({status}:{status:string}){return <span className={`status ${status}`}><span/>{status==='pending'?'Pending approval':status.charAt(0).toUpperCase()+status.slice(1)}</span>}
function Empty({text}:{text:string}){return <div className="empty"><Receipt size={28}/><p>{text}</p></div>}
function Stat({label,value,detail,icon:Icon,blue=false}:{label:string;value:string;detail:string;icon:typeof Wallet;blue?:boolean}){return <div className={`stat ${blue?'stat-blue':''}`}><div className="stat-label">{label}<Icon size={19}/></div><strong>{value}</strong><p>{detail}</p></div>}

export function ExpenseApp({platformOnly=false}:{platformOnly?:boolean}){
 const [data,setData]=useState<View|null>(null),[error,setError]=useState(''),[preview,setPreview]=useState(false),[activeId,setActiveId]=useState(''),[page,setPage]=useState('Overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Expense|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[category,setCategory]=useState(''),[role,setRole]=useState('employee'),[currency,setCurrency]=useState('KES');
 const [demoState,setDemoState]=useState<ReturnType<typeof initialState>|null>(null);
 useEffect(()=>{let live=true;fetch('/api/workspace').then(async r=>{const body=await r.json() as View & {error?:string};if(!r.ok){if(r.status===401&&['localhost','127.0.0.1'].includes(window.location.hostname)){const state=initialState('you@acacia.example');if(live){setDemoState(state);setData(visibleState(state,state.owner));setPreview(true);}return;}throw new Error(body.error);}if(live)setData(body);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false};},[]);
 useEffect(()=>{if(platformOnly)setPage('Platform admin');},[platformOnly]);
 const business=data?.businesses.find(b=>b.id===activeId)||data?.businesses[0];
 const myRole=business?.members.find(m=>m.email===data?.email)?.role;
 const canReview=myRole==='admin'||myRole==='manager',canAdmin=myRole==='admin',isEmployee=myRole==='employee';
 const pending=business?.expenses.filter(e=>e.status==='pending')||[],approved=business?.expenses.filter(e=>e.status==='approved')||[];
 const spend=approved.reduce((s,e)=>s+e.amount,0),pendingTotal=pending.reduce((s,e)=>s+e.amount,0),allocated=business?.ledger.filter(e=>e.amount>0).reduce((s,e)=>s+e.amount,0)||0;
 function navigate(next:string){setPage(next);setQuery('');setFilter('all');}
 function open(name:string,expense:Expense|null=null){setFormError('');setSelected(expense);setCategory(business?.categories[0]||'');setRole('employee');setModal(name);}
 async function act(payload:Record<string,unknown>){if(busy)return;setBusy(true);setFormError('');try{if(preview&&demoState){const next=structuredClone(demoState);mutate(next,data!.email,{businessId:business?.id,...payload});setDemoState(next);setData(visibleState(next,data!.email));}else{const response=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId:business?.id,...payload})});const body=await response.json() as View & {error?:string};if(!response.ok)throw new Error(body.error);setData(body);}toast.success(payload.action==='review'?'Expense decision recorded':'Changes saved');setModal('');}catch(e){const message=e instanceof Error?e.message:'Unable to save. Please try again.';setFormError(message);toast.error(message);}finally{setBusy(false);}}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));const amount=Number(fields.amount),cents=Math.round(amount*100);if('amount'in fields&&(!Number.isFinite(amount)||Math.abs(amount*100-cents)>0.00001)){setFormError('Enter an amount with at most two decimal places.');return;}const payload=modal==='expense'?{action:'submit',...fields,amount:cents,category}:modal==='allocate'?{action:'allocate',...fields,amount:cents}:modal==='category'?{action:'category',...fields}:modal==='member'?{action:'member',...fields,role}:modal==='business'?{action:'createBusiness',...fields,currency}:{action:'review',expenseId:selected?.id,status:'rejected',...fields};void act(payload);}
 const filtered=(page==='Approvals'?pending:business?.expenses||[]).filter(e=>(filter==='all'||e.status===filter)&&`${e.merchant} ${e.category} ${e.submittedBy}`.toLowerCase().includes(query.toLowerCase()));
 function exportExpenses(){if(!business)return;const safe=(s:string)=>`"${(/^[=+@\-\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')}"`;const csv=[['Merchant','Amount','Currency','Category','Date','Submitted by','Status'],...filtered.map(e=>[e.merchant,(e.amount/100).toFixed(2),business.currency,e.category,e.date,e.submittedBy,e.status])].map(row=>row.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='expenseiq-expenses.csv';a.click();URL.revokeObjectURL(url);}
 if(!data)return <main className="loading"><div className="brandmark"><Layers3/></div><h1>ExpenseIQ <span>Business</span></h1><p>{error||'Opening your workspace…'}</p>{error?<button className="primary" onClick={()=>window.location.reload()}>Try again</button>:<div className="loading-bar"/>}</main>;
 const nameOf=(email:string)=>business?.members.find(m=>m.email===email)?.name||email;
 const transactions=(items:Expense[],review=false)=><Table><TableHeader><TableRow><TableHead>Expense</TableHead><TableHead>Category</TableHead><TableHead>Submitted by</TableHead><TableHead>Date</TableHead><TableHead className="numeric">Amount</TableHead><TableHead>Status</TableHead>{review?<TableHead>Review</TableHead>:null}</TableRow></TableHeader><TableBody>{items.map(e=><TableRow key={e.id}><TableCell><button className="merchant" onClick={()=>open('details',e)}><span className="merchant-icon" style={{background:palettes[Math.max(business?.categories.indexOf(e.category)||0,0)%6]+'15',color:palettes[Math.max(business?.categories.indexOf(e.category)||0,0)%6]}}>{e.merchant.slice(0,1)}</span><span>{e.merchant}<small>EXP-{e.id.slice(-5).toUpperCase()}</small></span></button></TableCell><TableCell><span className="category-label">{e.category}</span></TableCell><TableCell>{nameOf(e.submittedBy)}</TableCell><TableCell className="muted nowrap">{shortDate(e.date)}</TableCell><TableCell className="numeric amount">{money(e.amount,business?.currency)}</TableCell><TableCell><Status status={e.status}/></TableCell>{review?<TableCell>{e.submittedBy===data.email?<small className="muted">Needs another reviewer</small>:canReview?<div className="review-actions"><button disabled={busy||business?.suspended} aria-label={`Approve ${e.merchant}`} onClick={()=>void act({action:'review',expenseId:e.id,status:'approved'})}><Check size={17}/></button><button disabled={busy||business?.suspended} aria-label={`Reject ${e.merchant}`} onClick={()=>open('reject',e)}><X size={17}/></button></div>:null}</TableCell>:null}</TableRow>)}</TableBody></Table>;
 return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href={platformOnly?'/platform':'/'}><span className="brandmark"><Layers3 size={23}/></span><span>Expense<span className="brand-iq">IQ</span><small>{platformOnly?'PLATFORM':'BUSINESS'}</small></span></a>{!platformOnly?<div className="workspace-select"><span className="company-icon"><Building2 size={18}/></span><div><small>WORKSPACE</small><Choice label="Business workspace" value={business?.id||''} onChange={v=>{setActiveId(v);navigate('Overview');}} options={data.businesses.map(b=>({value:b.id,label:b.name}))}/></div></div>:null}</SidebarHeader><SidebarContent>{platformOnly?<><div className="nav-caption">PLATFORM</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive className="nav-item" onClick={()=>navigate('Platform admin')}><Building2/><span>Admin dashboard</span><span className="admin-dot"/></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><a className="nav-item nav-link" href="/"><LayoutDashboard/><span>Business workspace</span></a></SidebarMenuItem></SidebarMenu></>:<><div className="nav-caption">WORKSPACE</div><SidebarMenu>{nav.filter(([label])=>!(isEmployee&&['Wallet','Categories','Team'].includes(label))).map(([label,Icon])=><SidebarMenuItem key={label}><SidebarMenuButton isActive={page===label} onClick={()=>navigate(label)} className="nav-item"><Icon/><span>{label}</span>{label==='Approvals'&&pending.length>0?<b className="nav-count">{pending.length}</b>:null}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></>}</SidebarContent><SidebarFooter><div className="sidebar-note"><ShieldCheck size={20}/><strong>{platformOnly?'Platform control room.':'Every expense, accountable.'}</strong><p>{platformOnly?'Company accounts, status, and growth at a glance.':'Clear approvals. Complete visibility.'}</p></div><div className="profile"><div className="avatar">{data.email.slice(0,2).toUpperCase()}</div><div><strong>{nameOf(data.email)}</strong><small>{platformOnly?'Platform admin':myRole==='admin'?'Business admin':myRole==='manager'?'Manager':myRole==='employee'?'Employee':'Workspace user'}</small></div></div></SidebarFooter></Sidebar><SidebarInset className="main-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>{platformOnly?'Platform':'Workspace'}</span><ChevronRight size={14}/><strong>{page}</strong></div><div className="topbar-right"><span className="workspace-status">{platformOnly?'Platform admin':business?.suspended?'Account suspended':'Business workspace'}</span>{data.platform&&!platformOnly?<a className="secondary topbar-link" href="/platform"><Building2 size={16}/>Admin login</a>:null}<button className="help-button" aria-label="Approval and wallet help" onClick={()=>open('help')}><CircleHelp size={20}/></button><div className="avatar small">{data.email.slice(0,2).toUpperCase()}</div></div></header>
 <main className="content"><div className="page-heading"><div><p className="eyebrow">{page==='Platform admin'?'YOUR PLATFORM':business?.name||'YOUR WORKSPACE'}</p><h1>{page==='Overview'?'Business overview':page==='Wallet'?'Company wallet':page==='Approvals'?'Expense approvals':page}</h1><p className="subtitle">{{Overview:'A clear picture of your company spending.',Expenses:'Track every expense, from submission to approval.',Approvals:'Keep business spending moving, with the right checks.',Wallet:'Allocate budgets and follow every movement.',Categories:'Organize spending around the way your business works.',Team:'The right access for everyone in your business.',Activity:'A record of the decisions behind your spending.','Platform admin':'Manage businesses across your expense platform.'}[page]}</p></div><div className="heading-actions">{page==='Platform admin'&&data.platform?<button className="primary" onClick={()=>open('business')}><Plus size={18}/>Add business</button>:page==='Team'&&canAdmin&&!platformOnly?<button className="primary" disabled={business?.suspended} onClick={()=>open('member')}><Plus size={18}/>Add team member</button>:page==='Categories'&&canAdmin&&!platformOnly?<button className="primary" disabled={business?.suspended} onClick={()=>open('category')}><Plus size={18}/>New category</button>:page==='Wallet'&&canAdmin&&!platformOnly?<button className="primary" disabled={business?.suspended} onClick={()=>open('allocate')}><Plus size={18}/>Allocate budget</button>:business&&myRole&&!platformOnly?<button className="primary" disabled={business.suspended} onClick={()=>open('expense')}><Plus size={18}/>New expense</button>:null}</div></div>
 {preview?<div className="notice">Local preview · Sample data. Changes last until this page is refreshed.</div>:business?.demo&&!platformOnly?<div className="notice">Sample workspace · Explore with example expenses, or <a href="/platform">open platform admin <ArrowRight size={14}/></a></div>:null}
 {platformOnly&&!data.platform?<section className="panel platform-gate"><span className="approval-symbol"><ShieldCheck size={24}/></span><h2>Platform admin login</h2><p>This dashboard is reserved for the owner account that created the ExpenseIQ Business platform.</p><a className="primary" href="/">Go to business workspace</a></section>:null}
 {business?.suspended&&!platformOnly?<div className="notice warning">This business is suspended. Expense submissions and changes are paused.</div>:null}
 {!business&&!platformOnly?<Empty text="You do not belong to a business yet. Ask a business admin to add your sign-in email."/>:null}
 {business&&page==='Overview'&&!platformOnly?<><div className="stats"><Stat label={isEmployee?'Your approved expenses':'Approved spending'} value={money(spend,business.currency)} detail={`${approved.length} approved expenses · all time`} icon={ArrowUpRight}/><Stat label="Pending approval" value={money(pendingTotal,business.currency)} detail={`${pending.length} expenses awaiting review`} icon={Clock3}/><Stat label={isEmployee?'Your submissions':'Available budget'} value={isEmployee?String(business.expenses.length):money(balance(business),business.currency)} detail={isEmployee?'Across all expense statuses':'Internal wallet balance'} icon={Wallet} blue/><Stat label={isEmployee?'Rejected expenses':'Team members'} value={isEmployee?String(business.expenses.filter(e=>e.status==='rejected').length):String(business.members.length)} detail={isEmployee?'Review the reason and resubmit':`${business.members.filter(m=>m.role!=='employee').length} admins & managers`} icon={Users}/></div><div className="dashboard-grid"><section className="panel spending-panel"><div className="panel-title"><div><h2>Spending overview</h2><p>Approved expenses over the last 30 days</p></div><span className="subtle-tag">{business.currency}</span></div><SpendingChart expenses={approved} currency={business.currency}/></section><section className="panel categories-panel"><div className="panel-title"><h2>Spend by category</h2><button className="text-button" onClick={()=>navigate('Categories')}>View all <ArrowRight size={15}/></button></div><CategoryChart business={business}/></section></div>{pending.length>0?<div className="approval-banner"><div className="approval-symbol"><ShieldCheck size={23}/></div><div><strong>{pending.length} expenses are waiting for approval</strong><p>{money(pendingTotal,business.currency)} in pending requests{canReview?' — ready for your review.':'.'}</p></div><button onClick={()=>navigate('Approvals')}>Review expenses <ArrowRight size={17}/></button></div>:null}<section className="panel"><div className="panel-title"><div><h2>Recent expenses</h2><p>Your latest business transactions</p></div><button className="text-button" onClick={()=>navigate('Expenses')}>View all expenses <ArrowRight size={16}/></button></div>{business.expenses.length?transactions(business.expenses.slice(0,5)):<Empty text="Your first expense starts here. Select New expense to submit it."/>}</section></>:null}
 {business&&['Expenses','Approvals'].includes(page)&&!platformOnly?<section className="panel"><div className="table-toolbar"><div className="searchbox"><Search size={17}/><input aria-label="Search expenses" placeholder="Search merchant, category or member…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="toolbar-right">{page==='Expenses'?<Choice label="Expense status" value={filter} onChange={setFilter} options={[{value:'all',label:'All statuses'},{value:'pending',label:'Pending approval'},{value:'approved',label:'Approved'},{value:'rejected',label:'Rejected'}]}/>:<span className="muted">{filtered.length} awaiting review</span>}<button className="secondary" onClick={exportExpenses}><Download size={16}/>Export CSV</button></div></div>{filtered.length?transactions(filtered,page==='Approvals'):<Empty text={query?'No expenses match your search.':page==='Approvals'?'All caught up. No expenses are waiting for approval.':'No expenses yet.'}/>}</section>:null}
 {business&&page==='Wallet'&&!isEmployee&&!platformOnly?<><div className="wallet-grid"><section className="wallet-card"><div><Layers3 size={25}/><span>EXPENSEIQ BUSINESS</span></div><p>Available budget</p><strong>{money(balance(business),business.currency)}</strong><div className="wallet-card-footer"><span>{business.name}<small>INTERNAL BUDGET WALLET</small></span><Wallet size={32}/></div></section><section className="panel wallet-summary"><h2>Budget at a glance</h2><dl><div><dt>Total allocated</dt><dd>{money(allocated,business.currency)}</dd></div><div><dt>Approved spending</dt><dd>{money(spend,business.currency)}</dd></div><div><dt>Pending requests</dt><dd>{money(pendingTotal,business.currency)}</dd></div></dl><Progress value={allocated?Math.min(spend/allocated*100,100):0}/><p className="muted">{allocated?Math.round(spend/allocated*100):0}% used. Pending requests are not deducted.</p></section></div><section className="panel"><div className="panel-title"><div><h2>Wallet activity</h2><p>Budget allocations and approved expense deductions</p></div><span className="subtle-tag">Internal funds only</span></div>{business.ledger.length?<Table><TableHeader><TableRow><TableHead>Transaction</TableHead><TableHead>Recorded by</TableHead><TableHead>Date</TableHead><TableHead className="numeric">Amount</TableHead></TableRow></TableHeader><TableBody>{[...business.ledger].sort((a,b)=>b.date.localeCompare(a.date)).map(e=><TableRow key={e.id}><TableCell><div className="ledger-title"><span className={e.amount>0?'credit-icon':'debit-icon'}>{e.amount>0?<ArrowDownLeft size={20}/>:<ArrowUpRight size={20}/>}</span><span>{e.note}<small>{e.amount>0?'Budget allocation':'Approved expense'}</small></span></div></TableCell><TableCell>{nameOf(e.actor)}</TableCell><TableCell>{shortDate(e.date)}</TableCell><TableCell className={`numeric amount ${e.amount>0?'credit':''}`}>{e.amount>0?'+':''}{money(e.amount,business.currency)}</TableCell></TableRow>)}</TableBody></Table>:<Empty text="Allocate a budget to start using your company wallet."/>}</section></>:null}
 {business&&page==='Categories'&&!platformOnly?<div className="category-grid">{business.categories.map((c,i)=>{const expenses=approved.filter(e=>e.category===c),total=expenses.reduce((s,e)=>s+e.amount,0);return <section className="panel category-card" key={c}><span className="category-icon" style={{color:palettes[i%6],background:palettes[i%6]+'16'}}><Tags size={21}/></span><h2>{c}</h2><strong>{money(total,business.currency)}</strong><p>{expenses.length} approved expenses</p><Progress value={spend?total/spend*100:0}/><small>{spend?Math.round(total/spend*100):0}% of approved spending</small></section>})}</div>:null}
 {business&&page==='Team'&&!isEmployee&&!platformOnly?<section className="panel"><div className="panel-title"><div><h2>Business team</h2><p>Members sign in using the exact email listed below.</p></div><span className="subtle-tag">{business.members.length} members</span></div><Table><TableHeader><TableRow><TableHead>Team member</TableHead><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Access</TableHead></TableRow></TableHeader><TableBody>{business.members.map(m=><TableRow key={m.email}><TableCell><div className="team-name"><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><strong>{m.name}{m.email===data.email?' (you)':''}</strong></div></TableCell><TableCell>{m.email}</TableCell><TableCell><span className={`role-label ${m.role}`}>{m.role==='admin'?'Business admin':m.role==='manager'?'Manager':'Employee'}</span></TableCell><TableCell className="muted">{m.role==='admin'?'Manage team, budgets & approvals':m.role==='manager'?'Submit & approve expenses':'Submit own expenses'}</TableCell></TableRow>)}</TableBody></Table><div className="panel-footnote">To change a role, add the member’s existing email again. Access also depends on the site’s sharing settings.</div></section>:null}
 {business&&page==='Activity'&&!platformOnly?<section className="panel"><div className="panel-title"><h2>Audit trail</h2><span className="subtle-tag">{business.audit.length} events</span></div>{business.audit.map(e=><div className="audit-row" key={e.id}><span className="audit-icon"><Activity size={18}/></span><div><strong>{e.action}</strong><p>{nameOf(e.actor)}</p></div><time>{new Date(e.date).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</time></div>)}</section>:null}
 {page==='Platform admin'&&data.platform&&platformOnly?<><div className="stats"><Stat label="Business accounts" value={String(data.businesses.length)} detail="Across your platform" icon={Building2}/><Stat label="Active businesses" value={String(data.businesses.filter(b=>!b.suspended).length)} detail="Enabled for expense management" icon={ShieldCheck}/><Stat label="Team memberships" value={String(data.businesses.reduce((s,b)=>s+b.members.length,0))} detail="Across all company workspaces" icon={Users}/><Stat label="Pending expenses" value={String(data.businesses.reduce((s,b)=>s+b.expenses.filter(e=>e.status==='pending').length,0))} detail="Awaiting business review" icon={Clock3}/></div><section className="panel"><div className="panel-title"><div><h2>Business accounts</h2><p>Each business has an independent team, wallet, and expense history.</p></div></div><Table><TableHeader><TableRow><TableHead>Business</TableHead><TableHead>Team</TableHead><TableHead>Wallet balance</TableHead><TableHead>Status</TableHead><TableHead>Manage</TableHead></TableRow></TableHeader><TableBody>{data.businesses.map(b=><TableRow key={b.id}><TableCell><a className="merchant" href="/"><span className="company-icon"><Building2 size={19}/></span><span>{b.name}<small>{b.demo?'Sample workspace':b.currency+' workspace'}</small></span></a></TableCell><TableCell>{b.members.length} members</TableCell><TableCell className="amount">{money(balance(b),b.currency)}</TableCell><TableCell><Status status={b.suspended?'suspended':'active'}/></TableCell><TableCell><button className="text-button" disabled={busy} onClick={()=>void act({action:'suspend',businessId:b.id})}>{b.suspended?'Reactivate':'Suspend'}</button></TableCell></TableRow>)}</TableBody></Table></section></>:null}
 <footer className="content-footer"><span>ExpenseIQ Business</span><span><ShieldCheck size={14}/> Accountable spending, together.</span></footer></main></SidebarInset>
 <Dialog open={Boolean(modal)} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{{expense:'Submit an expense',allocate:'Allocate wallet budget',category:'New expense category',member:'Add or update a team member',business:'Create a business',reject:'Reject expense',details:selected?.merchant||'Expense details',help:'How your workspace works'}[modal]}</DialogTitle><DialogDescription>{{expense:'Give your reviewer the details they need to approve this expense.',allocate:'Record an internal budget allocation. This does not move real money.',category:'Create a category that matches your business spending.',member:'Grant access by sign-in email. No invitation email will be sent.',business:'Create an isolated workspace and assign its first business admin.',reject:'Tell the submitter why this expense cannot be approved.',details:'Expense details and approval history.',help:'From expense submission to an accountable decision.'}[modal]}</DialogDescription></DialogHeader>
 {modal==='help'?<div className="help-content"><h3>1. Allocate a budget</h3><p>Business admins add internal budget to the company wallet.</p><h3>2. Submit expenses</h3><p>Team members select a category and explain the business purpose.</p><h3>3. Review independently</h3><p>Managers and admins approve or reject expenses. Nobody can approve their own submission.</p><h3>4. Follow the balance</h3><p>Approval deducts the expense once. Activity records every decision. Wallets track budgets only and do not hold real money.</p></div>:modal==='details'&&selected?<div className="expense-detail"><div className="detail-amount">{money(selected.amount,business?.currency)}<Status status={selected.status}/></div><dl><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Expense date</dt><dd>{shortDate(selected.date)}</dd></div><div><dt>Submitted by</dt><dd>{nameOf(selected.submittedBy)}</dd></div>{selected.reviewedBy?<div><dt>Reviewed by</dt><dd>{nameOf(selected.reviewedBy)}</dd></div>:null}</dl><h3>Business purpose</h3><p>{selected.description}</p>{selected.reason?<><h3>Rejection reason</h3><p>{selected.reason}</p></>:null}{selected.status==='pending'&&canReview&&selected.submittedBy!==data.email?<div className="form-actions"><button className="secondary" disabled={busy||business?.suspended} onClick={()=>open('reject',selected)}>Reject</button><button className="primary" disabled={busy||business?.suspended} onClick={()=>void act({action:'review',expenseId:selected.id,status:'approved'})}>Approve expense</button></div>:null}</div>:<form onSubmit={submit} className="app-form" key={modal}>
 {modal==='expense'?<><label>Merchant<input name="merchant" required maxLength={160} placeholder="e.g. Google Workspace"/></label><div className="form-grid"><label>Amount ({business?.currency})<input name="amount" type="number" min="0.01" step="0.01" required placeholder="0.00"/></label><label>Expense date<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} max={new Date().toISOString().slice(0,10)}/></label></div><label>Category<Choice label="Category" value={category} onChange={setCategory} options={(business?.categories||[]).map(c=>({value:c,label:c}))}/></label><label>Business purpose<textarea name="description" required maxLength={500} rows={3} placeholder="What was this expense for?"/></label></>:null}
 {modal==='allocate'?<><label>Amount ({business?.currency})<input name="amount" type="number" min="0.01" step="0.01" required placeholder="0.00"/></label><label>Allocation reference<input name="note" required maxLength={160} placeholder="e.g. October operating budget"/></label></>:null}
 {modal==='category'?<label>Category name<input name="name" required maxLength={60} placeholder="e.g. Professional services"/></label>:null}
 {modal==='member'?<><label>Full name<input name="name" required maxLength={80} placeholder="e.g. Amina Hassan"/></label><label>Sign-in email<input name="email" type="email" required placeholder="name@company.com"/></label><label>Role<Choice label="Role" value={role} onChange={setRole} options={[{value:'employee',label:'Employee — submit own expenses'},{value:'manager',label:'Manager — submit and approve'},{value:'admin',label:'Business admin — manage workspace'}]}/></label></>:null}
 {modal==='business'?<><label>Business name<input name="name" required maxLength={80} placeholder="e.g. Acacia Technologies"/></label><label>Business admin email<input name="adminEmail" type="email" required defaultValue={data.email}/></label><label>Wallet currency<Choice label="Currency" value={currency} onChange={setCurrency} options={['KES','USD','EUR','GBP','UGX','TZS'].map(c=>({value:c,label:c}))}/></label><p className="muted">This business starts with an empty wallet and no sample expenses.</p></>:null}
 {modal==='reject'?<label>Reason for rejection<textarea name="reason" required maxLength={500} rows={3} placeholder="Explain what needs to change…"/></label>:null}
 {formError?<p className="form-error" role="alert">{formError}</p>:null}<div className="form-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?'Saving…':{expense:'Submit for approval',allocate:'Allocate budget',category:'Create category',member:'Save team member',business:'Create business',reject:'Reject expense'}[modal]}</button></div></form>}
 </DialogContent></Dialog><Toaster position="bottom-right" richColors/></SidebarProvider>;
}

export default function Home(){
 return <ExpenseApp/>;
}

function SpendingChart({expenses,currency}:{expenses:Expense[];currency:string}){
 const now=new Date(),start=new Date(now);start.setDate(start.getDate()-29);start.setHours(0,0,0,0);
 const values=Array.from({length:6},(_,i)=>{const from=new Date(start);from.setDate(from.getDate()+i*5);const to=new Date(from);to.setDate(to.getDate()+5);return {label:shortDate(from.toISOString()),value:expenses.filter(e=>new Date(e.date)>=from&&new Date(e.date)<to).reduce((s,e)=>s+e.amount,0)}});
 const max=Math.max(...values.map(v=>v.value),100),total=values.reduce((s,v)=>s+v.value,0);
 return <div className="spending-chart"><div className="chart-total">{money(total,currency)}<span><span className="legend-dot"/> Approved spending</span></div><div className="bar-chart" role="img" aria-label={`Approved spending over 30 days: ${values.map(v=>`${v.label}: ${money(v.value,currency)}`).join('; ')}`}><div className="chart-gridlines"><span>{money(max,currency)}</span><span>{money(max/2,currency)}</span><span>0</span></div><div className="bars">{values.map((v,i)=><div className="bar-column" key={i}><div className="bar-track"><div className="bar" title={`${v.label}: ${money(v.value,currency)}`} style={{height:`${Math.max(v.value/max*100,v.value?2:0)}%`,background:i===values.length-1?'#3266e9':'#dce6fc'}}/></div><span>{v.label}</span></div>)}</div></div></div>;
}
function CategoryChart({business}:{business:Business}){const items=business.categories.map((c,i)=>({name:c,value:business.expenses.filter(e=>e.category===c&&e.status==='approved').reduce((s,e)=>s+e.amount,0),color:palettes[i%6]})).filter(i=>i.value>0),total=items.reduce((s,i)=>s+i.value,0);let offset=0;const stops=items.map(i=>{const start=offset;offset+=i.value/total*100;return `${i.color} ${start}% ${offset}%`}).join(',');return <><div className="donut" role="img" aria-label={items.map(i=>`${i.name} ${Math.round(i.value/total*100)}%`).join(',')||'No approved spending'} style={{background:total?`conic-gradient(${stops})`:'#e9edf5'}}><div><strong>{items.length}</strong><span>categories</span></div></div><div className="category-legend">{items.length?items.slice(0,4).map(i=><div key={i.name}><span className="legend-dot" style={{background:i.color}}/><span>{i.name}</span><strong>{Math.round(i.value/total*100)}%</strong></div>):<p className="muted">Approved expenses will appear here.</p>}{items.length>4?<small className="muted">+ {items.length-4} more categories</small>:null}</div></>}
